import { Product } from './types'

export const FALLBACK_STORAGE_BASKETS: Product[] = [
  {
    id: 'prod-taya-storage',
    databaseId: 101,
    name: 'Taya Storage Basket',
    slug: 'taya-storage-basket',
    description: 'Handwoven in Kenya from 100% natural sweetgrass and sisal. Perfect for laundry, blankets, and elegant living room organization.',
    excerpt: 'Handcrafted storage basket with fitted lid.',
    price: 89,
    compareAtPrice: 109,
    onSale: true,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg'],
    category: { name: 'Storage Baskets', slug: 'storage-baskets' },
    categories: ['Storage Baskets'],
    inStock: true,
    colors: ['Natural', 'Brown', 'Black'],
    dimensions: { height: 45, width: 38, depth: 38 },
    featured: true,
    bestSeller: true,
    limitedEdition: false,
    badge: 'best-seller',
    rating: 5,
    reviewCount: 42,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-wanjiru-storage',
    databaseId: 102,
    name: 'Wanjiru Storage Basket',
    slug: 'wanjiru-storage-basket',
    description: 'Striking geometric patterns handwoven by Kenyan artisans. Durable and statement-making.',
    excerpt: 'Geometric lidded basket in warm earth tones.',
    price: 95,
    onSale: false,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-34copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-34copy_800x.jpg'],
    category: { name: 'Storage Baskets', slug: 'storage-baskets' },
    categories: ['Storage Baskets'],
    inStock: true,
    colors: ['Natural', 'Red', 'Black'],
    dimensions: { height: 50, width: 40, depth: 40 },
    featured: true,
    bestSeller: false,
    limitedEdition: true,
    badge: 'limited-edition',
    rating: 5,
    reviewCount: 28,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-natty-storage',
    databaseId: 103,
    name: 'Natty Storage Basket',
    slug: 'natty-storage-basket',
    description: 'Compact storage basket with fitted lid. Ideal for nursery, toys, or discreet bathroom storage.',
    excerpt: 'Compact handwoven lidded storage basket.',
    price: 75,
    onSale: false,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-32copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-32copy_800x.jpg'],
    category: { name: 'Storage Baskets', slug: 'storage-baskets' },
    categories: ['Storage Baskets'],
    inStock: true,
    colors: ['Natural', 'Yellow', 'White'],
    dimensions: { height: 35, width: 30, depth: 30 },
    featured: false,
    bestSeller: false,
    limitedEdition: false,
    rating: 4.9,
    reviewCount: 19,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-astou-storage',
    databaseId: 104,
    name: 'Astou Storage Basket',
    slug: 'astou-storage-basket',
    description: 'Extra tall woven floor basket featuring intricate traditional Kenyan coil weaving.',
    excerpt: 'Tall freestanding storage basket.',
    price: 110,
    compareAtPrice: 130,
    onSale: true,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg'],
    category: { name: 'Storage Baskets', slug: 'storage-baskets' },
    categories: ['Storage Baskets'],
    inStock: true,
    colors: ['Natural', 'Blue', 'Brown'],
    dimensions: { height: 60, width: 42, depth: 42 },
    featured: true,
    bestSeller: false,
    limitedEdition: false,
    badge: 'on-sale',
    rating: 5,
    reviewCount: 33,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  }
]

export const FALLBACK_KITCHEN_DINING: Product[] = [
  {
    id: 'prod-faaiza-basket-set',
    databaseId: 201,
    name: 'Faaiza Basket (Set of 3)',
    slug: 'faaiza-basket-set',
    description: 'Nesting basket set for bread, fruit, and tabletop display. Handcrafted with natural sisal fibers.',
    excerpt: 'Set of 3 versatile kitchen and tabletop baskets.',
    price: 65,
    onSale: false,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-32copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-32copy_800x.jpg'],
    category: { name: 'Kitchen & Dining', slug: 'kitchen-dining' },
    categories: ['Kitchen & Dining'],
    inStock: true,
    colors: ['Natural', 'Brown', 'Yellow'],
    dimensions: { height: 12, width: 26, depth: 26 },
    featured: true,
    bestSeller: true,
    limitedEdition: false,
    badge: 'best-seller',
    rating: 5,
    reviewCount: 37,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-savanna-bread-basket',
    databaseId: 202,
    name: 'Savanna Bread Basket',
    slug: 'savanna-bread-basket',
    description: 'Oval handwoven bread basket with breathable sweetgrass weave, keeping pastries fresh and elegant.',
    excerpt: 'Handwoven oval tabletop bread basket.',
    price: 39,
    compareAtPrice: 48,
    onSale: true,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-34copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-34copy_800x.jpg'],
    category: { name: 'Kitchen & Dining', slug: 'kitchen-dining' },
    categories: ['Kitchen & Dining'],
    inStock: true,
    colors: ['Natural', 'Green'],
    dimensions: { height: 10, width: 32, depth: 20 },
    featured: false,
    bestSeller: false,
    limitedEdition: false,
    badge: 'on-sale',
    rating: 4.8,
    reviewCount: 15,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-nyika-fruit-bowl',
    databaseId: 203,
    name: 'Nyika Fruit Bowl',
    slug: 'nyika-fruit-bowl',
    description: 'Deep round centerpiece bowl for fresh fruit and pantry organization. Hand-dyed with plant extracts.',
    excerpt: 'Deep artisan centerpiece fruit bowl.',
    price: 49,
    onSale: false,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg'],
    category: { name: 'Kitchen & Dining', slug: 'kitchen-dining' },
    categories: ['Kitchen & Dining'],
    inStock: true,
    colors: ['Natural', 'Red', 'Black'],
    dimensions: { height: 15, width: 30, depth: 30 },
    featured: true,
    bestSeller: false,
    limitedEdition: false,
    rating: 5,
    reviewCount: 22,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  }
]

export const FALLBACK_WALL_BASKETS: Product[] = [
  {
    id: 'prod-serengeti-sun-wall',
    databaseId: 301,
    name: 'Serengeti Sun Wall Basket',
    slug: 'serengeti-sun-wall-basket',
    description: 'Vibrant sunburst wall basket designed to create an organic gallery wall. Equipped with hanging loop.',
    excerpt: 'Sunburst pattern decorative wall basket.',
    price: 55,
    onSale: false,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-34copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-34copy_800x.jpg'],
    category: { name: 'Wall Baskets', slug: 'wall-baskets' },
    categories: ['Wall Baskets'],
    inStock: true,
    colors: ['Natural', 'Yellow', 'Black'],
    dimensions: { height: 35, width: 35, depth: 6 },
    featured: true,
    bestSeller: true,
    limitedEdition: false,
    badge: 'best-seller',
    rating: 5,
    reviewCount: 48,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-kilifi-mandala-wall',
    databaseId: 302,
    name: 'Kilifi Mandala Wall Platter',
    slug: 'kilifi-mandala-wall-platter',
    description: 'Large flat woven wall platter showcasing symmetrical coastal Kenyan mandala motifs.',
    excerpt: 'Large geometric wall art basket platter.',
    price: 68,
    compareAtPrice: 80,
    onSale: true,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-35copy_800x.jpg'],
    category: { name: 'Wall Baskets', slug: 'wall-baskets' },
    categories: ['Wall Baskets'],
    inStock: true,
    colors: ['Natural', 'Brown', 'Blue'],
    dimensions: { height: 42, width: 42, depth: 5 },
    featured: true,
    bestSeller: false,
    limitedEdition: true,
    badge: 'limited-edition',
    rating: 5,
    reviewCount: 31,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  },
  {
    id: 'prod-rift-valley-geo-wall',
    databaseId: 303,
    name: 'Rift Valley Geo Wall Basket',
    slug: 'rift-valley-geo-wall-basket',
    description: 'Earthy neutral tones and dynamic chevron lines make this basket a timeless modern accent.',
    excerpt: 'Chevron patterned natural wall basket.',
    price: 48,
    onSale: false,
    image: 'https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-32copy_800x.jpg',
    images: ['https://expeditionsubsahara.com/cdn/shop/products/ES_Oct_Product-32copy_800x.jpg'],
    category: { name: 'Wall Baskets', slug: 'wall-baskets' },
    categories: ['Wall Baskets'],
    inStock: true,
    colors: ['Natural', 'Black', 'White'],
    dimensions: { height: 30, width: 30, depth: 5 },
    featured: false,
    bestSeller: false,
    limitedEdition: false,
    rating: 4.9,
    reviewCount: 14,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01'
  }
]

export const ALL_FALLBACK_PRODUCTS: Product[] = [
  ...FALLBACK_STORAGE_BASKETS,
  ...FALLBACK_KITCHEN_DINING,
  ...FALLBACK_WALL_BASKETS
]

export function getFallbackProductsByCategory(categorySlug: string): Product[] {
  switch (categorySlug) {
    case 'storage-baskets':
      return FALLBACK_STORAGE_BASKETS
    case 'kitchen-dining':
      return FALLBACK_KITCHEN_DINING
    case 'wall-baskets':
      return FALLBACK_WALL_BASKETS
    default:
      return ALL_FALLBACK_PRODUCTS
  }
}
